default: &default
  adapter: mysql2
  # encoding: unicode
  pool: 5
  username: codingchallenge
  password: india2020
  host: coding-challenge.csamkcs4ck98.us-east-1.rds.amazonaws.com
  port: 3306

development:
  <<: *default
  database: codingchallenge

test:
  <<: *default
  database: codingchallenge

production:
  <<: *default
  database: codingchallenge