source 'https://rubygems.org'

gem 'activerecord'
gem 'mysql2'
gem 'pry', require: false, group: :development
gem 'rake'
gem 'rubocop'
gem 'sinatra-activerecord'
gem 'simplecov', require: false, group: :test

group :test do
  gem 'rack-test'
  gem 'rspec'
end