source 'https://rubygems.org'

ruby '2.6.3'
gem 'mysql2'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'rake'
gem 'rubocop'
gem 'pry', require: false, group: :development
gem 'simplecov', require: false, group: :test


